//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textile.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int id { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string TypePaiement { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public System.DateTime DateEcheance { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
