//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Textile.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        public int id { get; set; }
        public string NomSociete { get; set; }
        public string Adresse { get; set; }
        public string NumeroTelephone { get; set; }
        public string Fax { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
    }
}
